[project]
name = "cvise"
authors = [{ name = "Martin Liška", email = "marxin.liska@gmail.com" }, { name = "Moritz Pflanzer", email = "moritz@pflanzer.eu" }]
maintainers = [{ name = "Martin Liška", email = "marxin.liska@gmail.com" }]
description = "C-Vise is a super-parallel Python port of the C-Reduce."
readme = "README.md"
license = { file = "COPYING" }
requires-python = ">=3.8"

[tool.ruff]
exclude = ["objdir"]

line-length = 120

[tool.ruff.lint]
# Enable UP031.
ignore = ["E501", "UP031"]
select = ["B", "E", "F", "W", "UP", "C4"] # consider: ["I", "RUF"]
preview = true

[tool.ruff.format]
quote-style="single"
